[2025-02-10T08:04:56.435+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_bigquery-test.fetch_spark_result manual__2025-02-10T08:04:55.236347+00:00 [queued]>
[2025-02-10T08:04:56.459+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_bigquery-test.fetch_spark_result manual__2025-02-10T08:04:55.236347+00:00 [queued]>
[2025-02-10T08:04:56.461+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-02-10T08:04:56.509+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): fetch_spark_result> on 2025-02-10 08:04:55.236347+00:00
[2025-02-10T08:04:56.520+0000] {standard_task_runner.py:60} INFO - Started process 2348 to run task
[2025-02-10T08:04:56.528+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'load_bigquery-test', 'fetch_spark_result', 'manual__2025-02-10T08:04:55.236347+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/load-bigquery-test.py', '--cfg-path', '/tmp/tmpl1sui8mz']
[2025-02-10T08:04:56.534+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask fetch_spark_result
[2025-02-10T08:04:56.578+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-10T08:04:56.668+0000] {task_command.py:423} INFO - Running <TaskInstance: load_bigquery-test.fetch_spark_result manual__2025-02-10T08:04:55.236347+00:00 [running]> on host deproject-airflow-scheduler
[2025-02-10T08:04:56.896+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='load_bigquery-test' AIRFLOW_CTX_TASK_ID='fetch_spark_result' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T08:04:55.236347+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T08:04:55.236347+00:00'
[2025-02-10T08:04:56.900+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load-bigquery-test.py", line 26, in fetch_spark_result
    result = ti.xcom_pull(tasks_id="extract_spark_output", key="df_result")
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'tasks_id'
[2025-02-10T08:04:56.929+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=load_bigquery-test, task_id=fetch_spark_result, execution_date=20250210T080455, start_date=20250210T080456, end_date=20250210T080456
[2025-02-10T08:04:56.963+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task fetch_spark_result (xcom_pull() got an unexpected keyword argument 'tasks_id'; 2348)
[2025-02-10T08:04:56.993+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-02-10T08:04:57.035+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
