[2025-02-19T08:17:45.689+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping_news_dag.scrapping_nytimes manual__2025-02-19T08:17:43.787472+00:00 [queued]>
[2025-02-19T08:17:45.708+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping_news_dag.scrapping_nytimes manual__2025-02-19T08:17:43.787472+00:00 [queued]>
[2025-02-19T08:17:45.709+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-02-19T08:17:45.740+0000] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): scrapping_nytimes> on 2025-02-19 08:17:43.787472+00:00
[2025-02-19T08:17:45.748+0000] {standard_task_runner.py:60} INFO - Started process 350 to run task
[2025-02-19T08:17:45.753+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'scraping_news_dag', 'scrapping_nytimes', 'manual__2025-02-19T08:17:43.787472+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/scraping-news-dag.py', '--cfg-path', '/tmp/tmpbplaa3xc']
[2025-02-19T08:17:45.757+0000] {standard_task_runner.py:88} INFO - Job 111: Subtask scrapping_nytimes
[2025-02-19T08:17:45.789+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-19T08:17:45.865+0000] {task_command.py:423} INFO - Running <TaskInstance: scraping_news_dag.scrapping_nytimes manual__2025-02-19T08:17:43.787472+00:00 [running]> on host deproject-airflow-scheduler
[2025-02-19T08:17:46.063+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scraping_news_dag' AIRFLOW_CTX_TASK_ID='scrapping_nytimes' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T08:17:43.787472+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-19T08:17:43.787472+00:00'
[2025-02-19T08:17:46.115+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraping-news-dag.py", line 25, in scrapping_nytimes
    from source import nyt
  File "/opt/airflow/dags/source/nyt.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-19T08:17:46.147+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=scraping_news_dag, task_id=scrapping_nytimes, execution_date=20250219T081743, start_date=20250219T081745, end_date=20250219T081746
[2025-02-19T08:17:46.173+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 111 for task scrapping_nytimes (No module named 'selenium'; 350)
[2025-02-19T08:17:46.211+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-02-19T08:17:46.261+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
